[Database]
FilePath = "data/raw/books.db"

[Authors]
DataOutputFile = "data/results/authors_stats.csv"
FigOutputFile = "images/top_rated_most_read.png"

[AuthorBibliography]
QueryPath = "./sql/author_bibliography.sql"
DataOutputFilePrefix = "data/tables/"

[Works]
DataOutputFile = "data/results/works_stats.csv"
FigOutputFile = "images/work_score_scatter.png"

[ReadHistory]
ReadHistoryDataFile = "data/processed/read_history.csv"
QueryPath = "./sql/read_history.sql"
RecentReadsDataFile = "data/results/recent_reads.csv"

[NextReads]
QueryPath = "./sql/to_read_next.sql"
OutputFile = "data/tables/next_reads.md"

[Genres]
DataOutputFile = "data/results/genres_stats.csv"
FigOutputFile = "images/genres_scatter.png"
